# Generated by Django 5.0.4 on 2024-04-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wear_swaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
