# Generated by Django 5.0.4 on 2024-04-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wear_swaps', '0002_registereduser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
