# Generated by Django 5.0.3 on 2024-05-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wear_swaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
