# Generated by Django 5.0.4 on 2024-05-06 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wear_swaps', '0002_registereduser_age_registereduser_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_produto', models.CharField(choices=[('calca', 'Calça'), ('bermuda', 'Bermuda'), ('camisa', 'Camisa'), ('tenis', 'Tênis'), ('acessorio', 'Acessório')], max_length=20)),
                ('tamanho', models.CharField(blank=True, choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=5, null=True)),
                ('condicao', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='items')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wear_swaps.produto')),
            ],
        ),
    ]
