# Generated by Django 5.0.4 on 2024-05-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wear_swaps', '0007_produto_imagem_registereduser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='items'),
        ),
        migrations.AlterField(
            model_name='itemadicionado',
            name='imagem',
            field=models.ImageField(upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='lojaitem',
            name='imagem',
            field=models.ImageField(upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
