# Generated by Django 5.0.4 on 2024-05-30 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wear_swaps', '0008_alter_item_foto_alter_itemadicionado_imagem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto1',
        ),
    ]
